Tudor
Andreimdvn/iss_blood pull request #30
Opened 2018-05-13 19:20 UTC by TudorNan

2018-05-14 18:26 UTC, Andreimdvn submitted a review, later dismissed
rezolva gui-ul, fa mai vizibile butoanele cu "am inteles" si "inapoi", x-ul in dreapta
dupa ce apas am inteles sa se faca tranzitia la FormularDonareView.fxml
am warningul asta cand apas "am inteles": "WARNING: Could not resolve '-fx-primary-text-color' while resolving lookups for '-fx-text-fill'"

2018-05-14 18:26 UTC, Andreimdvn commented on .idea/IssBlood.iml
> +<?xml version="1.0" encoding="UTF-8"?>
nu da push din .idea, nu ar trebui sa te lase .gitignore, dar totusi fa un comit in care sa stergi asta

2018-05-14 18:26 UTC, Andreimdvn commented on Iss_blood_front/src/main/java/Controller/IstoricDonariController.java
> +import sun.rmi.runtime.Log;
nu e nevoie de asta

2018-05-18 15:48 UTC, MoldovanDaniel requested changes
AnchorPaneul cu text din Formular1 de la donator iese din ecran

2018-05-18 16:28 UTC, MoldovanDaniel submitted a review, later dismissed

2018-05-18 16:31 UTC, alinoancea approved these changes
Ok

2018-05-18 16:32 UTC, merged